---
- hosts: all
  become: yes
  gather_facts: no

  tasks:
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: install node 
    shell: |
      if ! command -v node; then
        curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs
      fi

  - name: Creates directory
    file:
      path: /bootcamp-app
      state: directory 

  - name: Clone a github repository
    git:
      repo: https://github.com/galfrylich/bootcamp-app.git
      dest: /home/bootcamp-app
      clone: yes
      update: yes

  - name: Install packages based on package.json using the npm
    npm:
      path: /home/bootcamp-app
      state: present

  - name: run initdb script
    run_once: true
    shell: cd /home/bootcamp-app && npm run initdb
    register: initdb
    tags:
      - initdb


  
  - name: install pm2
    npm:
      name: pm2
      global: yes

   
  - name: copy pm2 file to remote servers
    ansible.builtin.copy:
      src: /home/ansible/pm2start.sh
      dest: /home/bootcamp-app/pm2start.sh
      mode: '0755'

  - name: copy .env file to remote servers
    ansible.builtin.copy:
      src: /home/ansible/.env
      dest: /home/bootcamp-app/.env
      mode: '0755'    

  
  
  - name: Execute the script
    command: sh /home/bootcamp-app/pm2start.sh


  






